networks:
  proxy-net:
    external: true

services:
  lend-fam:
    image: ${IMAGE_NAME:-ghcr.io/lend-fam/frontend:latest}
    container_name: lend-fam
    networks:
      - proxy-net
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /tmp
