modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200, 301, 302]
      method: GET
      headers:
        Host: lend.family
        User-Agent: "Blackbox Exporter"
      follow_redirects: true
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: "ip4"

  http_post:
    prober: http
    timeout: 5s
    http:
      method: POST
      headers:
        Content-Type: application/json
      body: '{}'

  tcp_connect:
    prober: tcp
    timeout: 5s

  icmp:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"

  dns:
    prober: dns
    timeout: 10s
    dns:
      query_name: "lend.family"
      query_type: "A"
      valid_rcodes:
      - NOERROR
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false
      transport_protocol: "udp"
      dns_over_tls: false

  ssl_expiry:
    prober: http
    timeout: 5s
    http:
      method: GET
      fail_if_not_ssl: true
      tls_config:
        insecure_skip_verify: false